// components/index/Projects.vue
<template>
    <section class="projects pt-[70px] px-0 pb-[130px] relative">
        <div class="cntnr">
            <h2 class="section-title" delay="1000">
                <img src="/images/projects/icon.svg" alt="" class="max-w-[50px] mr-4">
                <span>projects</span>
            </h2>
            <p class="mini-title">Browse through the latest websites I developed which I consider "highlights"</p>
            <div class="projects-wrapper flex justify-between flex-row flex-wrap mt-8 duration-500">
                <div v-for="(project, key) in projects" :key="key" class="box flex-shrink-0 flex-grow-0 w-full md:w-1/2 py-4 px-0 md:px-4 duration-500">
                    <div class="real-box w-full flex flex-col py-5 px-5 h-full relative duration-500 shadow-teal hover:shadow-teal-glow group">
                        <a rel="noopener" :href="project.agency.url" target="_blank" class="agency absolute max-w-[120px] w-full duration-500  opacity-1 md:opacity-0 group-hover:opacity-100">
                            <img :src="`/images/projects/agencies/${project.agency.logo}`" alt="" class="w-full">
                        </a>
                        <div class="top w-full pt-[55%] relative overflow-hidden">
                            <picture v-lazy-load>
                                <source :srcset="`/images/projects/websites/${project.id}.webp`" type="image/webp">
                                <img width="100%" height="100%" :src="`/images/projects/websites/${project.id}.png`" :alt="project.name" v-lazy-load class="absolute w-full h-full object-cover top-0 left-0 bottom-0 right-0"/>
                            </picture>
                        </div>
                        <div class="bottom my-5 flex flex-col justify-between h-full">
                            <div class="texts flex flex-row flex-wrap">
                                <p class="name font-fira-code font-semibold text-2xl mb-1 text-red dark:text-yellow flex-[100%] duration-500">{{ project.name }}</p>
                                <p class="description text-sm flex-[100%] text-dark-blue dark:text-teal duration-500">{{ project.description }}</p>
                            </div>
                            <a rel="noopener" :href="project.url" target="_blank" class="button mt-2 text-dark-blue dark:text-teal block dark:bg-dark-blue text-center self-end text-base border border-dark-blue dark:border-teal hover:bg-dark-blue hover:text-teal dark:hover:bg-teal dark:hover:text-dark-blue">VISIT SITE ➹</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="waves absolute bottom-[-1px] left-0 w-full overflow-hidden leading-[0] rotate-180">
            <svg data-name="Layer 1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 120" preserveAspectRatio="none" class="relative block h-[75px] md:h-[78px]">
                <path d="M0,0V46.29c47.79,22.2,103.59,32.17,158,28,70.36-5.37,136.33-33.31,206.8-37.5C438.64,32.43,512.34,53.67,583,72.05c69.27,18,138.3,24.88,209.4,13.08,36.15-6,69.85-17.84,104.45-29.34C989.49,25,1113-14.29,1200,52.47V0Z" opacity=".25" class="shape-fill"></path>
                <path d="M0,0V15.81C13,36.92,27.64,56.86,47.69,72.05,99.41,111.27,165,111,224.58,91.58c31.15-10.15,60.09-26.07,89.67-39.8,40.92-19,84.73-46,130.83-49.67,36.26-2.85,70.9,9.42,98.6,31.56,31.77,25.39,62.32,62,103.63,73,40.44,10.79,81.35-6.69,119.13-24.28s75.16-39,116.92-43.05c59.73-5.85,113.28,22.88,168.9,38.84,30.2,8.66,59,6.17,87.09-7.5,22.43-10.89,48-26.93,60.65-49.24V0Z" opacity=".5" class="shape-fill"></path>
                <path d="M0,0V5.63C149.93,59,314.09,71.32,475.83,42.57c43-7.64,84.23-20.12,127.61-26.46,59-8.63,112.48,12.24,165.56,35.4C827.93,77.22,886,95.24,951.2,90c86.53-7,172.46-45.71,248.8-84.81V0Z" class="shape-fill"></path>
            </svg>
        </div>
    </section>
</template>

<script>
    export default {
        data: () => ({
            projects: [
                {
                    id: 'kogs',
                    name: 'KOGs',
                    url: 'https://kogs.gg/',
                    description: `Buy these highly collectible, easily transferrable non-fungible tokens (NFTs) here. Play to Earn!`,
                    agency: {
                        logo: 'designblue.svg',
                        url: 'https://designbluemanila.com/'
                    }
                },
                {
                    id: 'ride-revolution',
                    name: 'Ride Revolution',
                    url: 'https://www.riderevolution.ph/',
                    description: `A platform where you can buy packages and book your classes from this very nice indoor cycling studio. Achieve fitness!`,
                    agency: {
                        logo: 'designblue.svg',
                        url: 'https://designbluemanila.com/'
                    }
                },
                {
                    id: 'koreatayosoon',
                    name: 'KoreaTayoSoon',
                    url: 'https://koreatayosoon.ph/',
                    description: `Join the Creative Contest by Korea Tourism Organization and win AMAZING prizes such as ROUNDTRIP TICKETS TO KOREA`,
                    agency: {
                        logo: 'designblue.svg',
                        url: 'https://designbluemanila.com/'
                    }
                },
                {
                    id: 'ggtc',
                    name: 'GGTC',
                    url: 'https://ggtc.world/',
                    description: `Make a difference! Save lives by countering tobacco industry interference.`,
                    agency: {
                        logo: 'designblue.svg',
                        url: 'https://designbluemanila.com/'
                    }
                },
                {
                    id: 'manila-ocean-park',
                    name: 'Manila Ocean Park',
                    url: 'https://www.manilaoceanpark.com/',
                    description: `Philippines' first world-class marine theme park. Buy tickets and book from here!`,
                    agency: {
                        logo: 'designblue.svg',
                        url: 'https://designbluemanila.com/'
                    }
                },
            ]
        }),
        mounted () {
            let targets = [
                `section.projects > div.cntnr > h2`,
                `section.projects > div.cntnr > .mini-title`,
                `section.projects > div.cntnr > div .box`
            ]

            this.animateElements(targets)
        }
    }
</script>

<style>
    .waves svg {
        width: calc(100% + 1.3px);
    }
    .waves svg .shape-fill {
        fill: #22b4ab;
    }
    .agency {
        bottom: calc(100% - 13px);
    }
</style>

// src/components/pages/index/Projects.svelte
<section class="projects relative overflow-hidden">
  <svg class="absolute left-0 bottom-0 opacity-10 2xl:w-full 2xl:h-full" xmlns="http://www.w3.org/2000/svg" version="1.1" xmlns:xlink="http://www.w3.org/1999/xlink" width="1366" height="1366" preserveAspectRatio="none" viewBox="0 0 1366 1366">
      <g fill="none">
          <path d="M577.15-10.32C379.09 168.88 432.82 936.31 173.01 978.68-86.8 1021.05-104.39 682.24-231.13 664.5" class="stroke-dark dark:stroke-primary transition-colors duration-300" stroke-width="2"></path>
          <path d="M871.02-91.5C685.82 201.49 835.78 1225.02 536.63 1254.02 237.48 1283.02 100.02 627.61-132.16 571.02" class="stroke-dark dark:stroke-primary transition-colors duration-300" stroke-width="2"></path>
          <path d="M806.51-168.46C627.4 56.01 769.64 901.04 468.22 929.28 166.81 957.52-7.82 510.62-208.35 492.16" class="stroke-dark dark:stroke-primary transition-colors duration-300" stroke-width="2"></path>
          <path d="M1172.63-30.36C938.93 44.36 866.76 717.42 540.12 720.05 213.48 722.68 96.96 315.54-92.39 296.59" class="stroke-dark dark:stroke-primary transition-colors duration-300" stroke-width="2"></path>
          <path d="M725.8-115.59C514.64 127.57 589.79 1053.54 319.51 1106.86 49.23 1160.18 62.82 675.92-86.78 628.76" class="stroke-dark dark:stroke-primary transition-colors duration-300" stroke-width="2"></path>
      </g>
      <defs>
          <mask id="SvgjsMask1039">
              <rect width="1366" height="1366" fill="#ffffff"></rect>
          </mask>
      </defs>
  </svg>

  <div class="container py-10 lg:py-20 relative">
    <div class="heading">
      <h1>
        <svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" viewBox="0 0 24 24"><path d="M22 2v20h-20v-20h20zm2-2h-24v24h24v-24zm-4 7h-8v1h8v-1zm0 5h-8v1h8v-1zm0 5h-8v1h8v-1zm-10.516-11.304l-.71-.696-2.553 2.607-1.539-1.452-.698.71 2.25 2.135 3.25-3.304zm0 5l-.71-.696-2.552 2.607-1.539-1.452-.698.709 2.249 2.136 3.25-3.304zm0 5l-.71-.696-2.552 2.607-1.539-1.452-.698.709 2.249 2.136 3.25-3.304z"/></svg>
        <span>projects</span>
      </h1>
      <p>My favorite websites I have worked on</p>
    </div>
    <div class="flex justify-start flex-wrap mt-5 xl:mt-10">
      {#each projects as project}
        <div class="project-box w-full md:w-1/2 py-4 px-0 md:px-4">
          <div class="rounded-2xl relative group flex-col transition-shadow duration-300 shadow-[0px_1px_8px_0px_#00000020] dark:shadow-[0px_1px_8px_0px_#06b6d430]">
            <a href={project.agency.url} target="_blank" class="agency absolute max-w-[85px] md:max-w-[120px] w-full shadow-sm hover:shadow-md hover:shadow-primary shadow-primary transition-all duration-300 opacity-1 xl:opacity-0 group-hover:opacity-100 bg-dark px-3 py-2 rounded-xl z-[2] top-0 left-5 -translate-y-1/2">
              <img class="lazy" src="/images/extras/loading.svg" data-src="/images/projects/agencies/{ project.agency.logo }" data-srcset="/images/projects/agencies/{ project.agency.logo }" alt="designblue">
            </a>
            <div class="pt-[60%] xl:pt-[70%] relative w-full rounded-t-2xl xl:rounded-b-2xl overflow-hidden">
              <img class="lazy image-cover" src="/images/extras/loading.svg" data-src="/images/projects/websites/{ project.id }.png" data-srcset="/images/projects/websites/{ project.id }.png" alt={ project.name }>
            </div>
            <div class="flex flex-col p-5 xl:hidden bg-white dark:bg-dark rounded-b-xl">
              <p class="font-semibold mb-5 text-lg text-dark dark:text-white">{ project.name }</p>
              <a href={project.url} target="_blank" class="btn btn-primary has-image">
                <span>VISIT WEBSITE</span>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-white"><path d="M21 13v10h-21v-19h12v2h-10v15h17v-8h2zm3-12h-10.988l4.035 4-6.977 7.07 2.828 2.828 6.977-7.07 4.125 4.172v-11z"/></svg>
              </a>
            </div>
            <div class="overlay absolute hidden xl:flex flex-col justify-center items-center w-full h-full top-0 left-0 m-auto transition-colors duration-300 bg-dark rounded-2xl bg-opacity-0 group-hover:bg-opacity-80">
              <p class="text-white font-bold text-2xl mb-3 text-center max-w-[300px] w-full transition-all duration-300 -translate-y-5 opacity-0 group-hover:translate-y-0 group-hover:opacity-100">{ project.name }</p>
              <a href={project.url} target="_blank" class="btn btn-primary has-image transition-all translate-y-5 opacity-0 group-hover:translate-y-0 group-hover:opacity-100">
                <span>VISIT WEBSITE</span>
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" class="fill-white"><path d="M21 13v10h-21v-19h12v2h-10v15h17v-8h2zm3-12h-10.988l4.035 4-6.977 7.07 2.828 2.828 6.977-7.07 4.125 4.172v-11z"/></svg>
              </a>
            </div>
          </div>
        </div>
      {/each}
    </div>
  </div>
</section>

<script>
  /* data */
  let projects = [
    {
      id: 'manila-ocean-park',
      name: 'Manila Ocean Park',
      url: 'https://www.manilaoceanpark.com/',
      description: `Philippines' first world-class marine theme park. Buy tickets and book from here!`,
      agency: {
        logo: 'designblue.svg',
        url: 'https://designbluemanila.com/'
      }
    },
    {
      id: 'kogs',
      name: 'KOGs',
      url: 'https://kogs.gg/',
      description: `Buy these highly collectible, easily transferrable non-fungible tokens (NFTs) here. Play to Earn!`,
      agency: {
        logo: 'designblue.svg',
        url: 'https://designbluemanila.com/'
      }
    },
    {
      id: 'ride-revolution',
      name: 'Ride Revolution',
      url: 'https://www.riderevolution.ph/',
      description: `A platform where you can buy packages and book your classes from this very nice indoor cycling studio. Achieve fitness!`,
      agency: {
        logo: 'designblue.svg',
        url: 'https://designbluemanila.com/'
      }
    },
    {
      id: 'ggtc',
      name: 'GGTC',
      url: 'https://ggtc.world/',
      description: `Make a difference! Save lives by countering tobacco industry interference.`,
      agency: {
        logo: 'designblue.svg',
        url: 'https://designbluemanila.com/'
      }
    },
  ]
</script>
